### ISSUE TITLE
Extract HdInputPassword from HdInput

### ISSUE THREAD

**Issue by viniciuskneves** [homeday-de/homeday-blocks#203]
Currently [`HdInput`](https://github.com/homeday-de/homeday-blocks/blob/develop/src/components/form/HdInput.vue) has some extra logic on top to handle `password` type. It could be extracted into another component to make it clear and don't overwhelm `HdInput` with logic.
We're currently developing also `HdInputFormatter` that should be possible to handle formatting inside `HdInput` but it is build on top of `HdInput` to not add extra logic layer into it.

**Comment by ladas-larry** [comment]
Would you close this one? @viniciuskneves

**Comment by viniciuskneves** [comment]
Hey @ladas-larry, this issue was tackled by @aym3nb already.

Check #250 for more details.

Did you find any further issues/improvements here that you would like to suggest/work on?

Thanks for asking!

**Comment by ladas-larry** [comment]
Hi Vinicius, I see, thanks!

I'm looking for an opportunity to contribute to this repo.

I have further questions regarding https://github.com/homeday-de/homeday-blocks/issues/281, please have a look there.

Or if you have any task at your hands, that can be assign as a new issue, please open it and will follow up. :)

**Comment by viniciuskneves** [comment]
Hey @ladas-larry thanks for your interest!

I will check #281 with @drapisarda to see if it still relevant and if he can provide more info there.

I will take some time tomorrow to move some "private" issues to GitHub, we have a bunch of tickets on our Jira board.

Get back to you tomorrow =]

**Comment by ladas-larry** [comment]
Hi @viniciuskneves,
how has been your investigation of the tickets?
Any updates on that?

**Comment by viniciuskneves** [comment]
Hey @ladas-larry, wanna give it a shot for this topic (https://github.com/homeday-de/homeday-blocks/pull/402#discussion_r406207406)?

We are discussing about having a mixin implementation but we're not sure yet how it would look like or so. You can give it a try and we can discuss about it in the PR. What do you think?
