### ISSUE TITLE
Rewrite HdResponsive to use MediaQueryList.addListener

### ISSUE THREAD

**Issue by OriginalEXE** [homeday-de/homeday-blocks#222]
For the HdResponsive component, right now we rely on the resize event to check and update the matching breakpoints. It's throttled so there is no huge performance hit, but we could instead set up listeners on each media query, which fire only once (when the change happens).

More docs here: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener

It is well supported in all browsers we care about. The only "complexity" is that the recommendation is to use `addEventListener` instead of `addListener`, but `addEventListener` is not available in Safari. This can be solved by checking for existence and calling the appropriate one. Their functionality is the same.

**Comment by drapisarda** [comment]
Working on this

**Comment by drapisarda** [comment]
My proposal https://github.com/homeday-de/homeday-blocks/pull/299
