### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by pooriyad** [homeday-de/homeday-blocks#456]
I cloned the repo and installed the dependencies. When I run the unit test, it fails.

Summary of failing test:
```
 FAIL  tests/unit/components/notifications/HdNotifications.spec.js
  ● HdNotifications › fires the heightChange event when height of the notifications changes

    expect(received).toBeTruthy()

    Received: undefined

      46 |     await wrapper.vm.$nextTick();
      47 | 
    > 48 |     expect(wrapper.emitted('heightChange')).toBeTruthy();
         |                                             ^
      49 |   });
      50 | });
      51 | 
```

**Comment by viniciuskneves** [comment]
Hey @pooriyad, could you check this comment and see if you're having the same issue? https://github.com/homeday-de/homeday-blocks/pull/441#discussion_r427396918

**Comment by pooriyad** [comment]
Thanks @viniciuskneves for your fast response. Yeah, changing the node version fixed it.
